# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a3e2c3fcd8bdf16d3041ebee999dac7ebd8bcb8ac075610d9108c30f9c0655bdb487276ffbba6627b92ceb27a2bfead7671e135359e0b7df19a7769e6c832cf

test:
  secret_key_base: 5aaacd395991b3f00fbcbdcc162305becf05549309582d14ea70bf5412e9c070dbfd8cbe11a0d40ea3b138d59a4175fb041a14640608d81014882323f0652597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
